import './globals.css'

//@ts-ignore
import FullSizeNav from "/src/app/Navbar/Navbar.tsx"; //@ts-ignore
import MiniNav from "/src/app/Navbar/MiniNav.tsx"; //@ts-ignore

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="">
      <body className='min-h-screen flex flex-col bg-gray-light text-black'>
        <FullSizeNav />
        <MiniNav />
        <main className="flex grow">
        {children}
        </main>
        <div className="flex w-full justify-center block text-xs">Eli Lewis</div>
      </body>
    </html>
  )
}
